package approval

import (
	"context"
	"path/filepath"
	"strings"
)

// Gate checks commands against a whitelist, then calls the Approver
// for commands that are not whitelisted.
type Gate struct {
	whitelist map[string]struct{}
	approver  Approver
}

func NewGate(whitelist []string, approver Approver) *Gate {
	m := make(map[string]struct{}, len(whitelist))
	for _, w := range whitelist {
		m[w] = struct{}{}
	}
	return &Gate{whitelist: m, approver: approver}
}

// Check returns (Decision, nil) on success, (zero Decision, err) on approver failure.
// Whitelisted commands return Decision{Allow: true} immediately without calling the approver.
// digest should be pre-generated by the caller so that all log entries for this
// command share the same correlation token.
func (g *Gate) Check(ctx context.Context, user, host, remoteIP, sessionID, command, digest string) (Decision, error) {
	if g.isWhitelisted(command) {
		return Decision{Allow: true}, nil
	}
	return g.approver.RequestApproval(ctx, user, host, remoteIP, command, digest)
}

func (g *Gate) isWhitelisted(command string) bool {
	if containsAmbiguous(command) {
		return false
	}
	tokens := splitCompound(command)
	if len(tokens) == 0 {
		return false
	}
	for _, tok := range tokens {
		if !g.tokenWhitelisted(tok) {
			return false
		}
	}
	return true
}

func (g *Gate) tokenWhitelisted(segment string) bool {
	segment = strings.TrimSpace(segment)
	fields := strings.Fields(segment)
	if len(fields) == 0 {
		return true
	}
	name := filepath.Base(fields[0])
	_, ok := g.whitelist[name]
	return ok
}

func containsAmbiguous(cmd string) bool {
	return strings.Contains(cmd, "$(") ||
		strings.Contains(cmd, "`") ||
		strings.Contains(cmd, "{") ||
		strings.Contains(cmd, "<(") ||
		strings.Contains(cmd, ">(")
}

func splitCompound(cmd string) []string {
	var result []string
	var buf strings.Builder
	inSingleQuote := false
	inDoubleQuote := false

	for i := 0; i < len(cmd); i++ {
		c := cmd[i]

		switch c {
		case '\'':
			if !inDoubleQuote {
				inSingleQuote = !inSingleQuote
			}
			buf.WriteByte(c)
		case '"':
			if !inSingleQuote {
				inDoubleQuote = !inDoubleQuote
			}
			buf.WriteByte(c)
		case '&':
			if !inSingleQuote && !inDoubleQuote {
				if i+1 < len(cmd) && cmd[i+1] == '&' {
					if buf.Len() > 0 {
						result = append(result, strings.TrimSpace(buf.String()))
						buf.Reset()
					}
					i++ // skip next &
				} else {
					buf.WriteByte(c)
				}
			} else {
				buf.WriteByte(c)
			}
		case '|':
			if !inSingleQuote && !inDoubleQuote {
				if i+1 < len(cmd) && cmd[i+1] == '|' {
					if buf.Len() > 0 {
						result = append(result, strings.TrimSpace(buf.String()))
						buf.Reset()
					}
					i++ // skip next |
				} else {
					if buf.Len() > 0 {
						result = append(result, strings.TrimSpace(buf.String()))
						buf.Reset()
					}
				}
			} else {
				buf.WriteByte(c)
			}
		case ';':
			if !inSingleQuote && !inDoubleQuote {
				if buf.Len() > 0 {
					result = append(result, strings.TrimSpace(buf.String()))
					buf.Reset()
				}
			} else {
				buf.WriteByte(c)
			}
		default:
			buf.WriteByte(c)
		}
	}

	if buf.Len() > 0 {
		result = append(result, strings.TrimSpace(buf.String()))
	}

	return result
}
